### ISSUE TITLE
Side note: NFT hack

### ISSUE THREAD

**Issue by pet3r-pan** [lenara/plantary#2]
Just a small side note, we are also running the Untitled NFT hackathon that is ending on the 27th of Oct (6PM PST)

Feel free to submit your hack to this hackathon as well if you wish :)

https://medium.com/nfthack/untitled-nft-hack-submissions-e1418a3fbfda

**Comment by lenara** [comment]
Thanks! Submitted, and took the opportunity to write the beginnings of our admin interface using arweave.
